delete http://localhost:3003/api/blogs/696e88bb9d6b748de27bea6d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzc3Vza2EiLCJpZCI6IjY5NmUzY2NhMDJhNTY5NjQwNzU2ODBiMiIsImlhdCI6MTc2ODg1MTI1NH0.reSMHF9ZOUx7RUPhjJm_5Wsukn77g1X3w4H5rHhHm0o