delete http://localhost:3003/api/blogs/696e319c01cc0ba91c36d62e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzc3Vza2EiLCJpZCI6IjY5NmUzY2NhMDJhNTY5NjQwNzU2ODBiMiIsImlhdCI6MTc2ODgzNjIyMH0.Lo0_v9-KZoRuI-LPEasP7_YdWtUAfd7E2oYaRZxZ7Ao