post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzc3Vza2EiLCJpZCI6IjY5NmUzY2NhMDJhNTY5NjQwNzU2ODBiMiIsImlhdCI6MTc2ODgzNTM0N30.kY68ngXByP51HUTYGcJcVyuGvfD3kVI5wxMHceBjyAM

{
    "title": "Test for 4.20 exercise",
    "author": "Minä",
    "url": "https//testblog0348.com",
    "likes": 100
}